version: 1
services:
  - type: web
    name: shequ-backend
    env: node
    rootDir: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_NAME
        value: shequ
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_lxN2uHQYSiZ5
      - key: DB_HOST
        value: ep-little-credit-a4ljft2f-pooler.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        value: your_super_secure_jwt_secret_key_2024
    region: oregon
    plan: free
    healthCheckPath: /